add fps micro asset
only one error:
AssertionException: Assertion failure. Value was Null
Expected: Value was not Null
UnityEngine.Assertions.Assert.Fail (System.String message, System.String userMessage) (at <94c5f4c38cdc42d2b006f8badef04394>:0)
UnityEngine.Assertions.Assert.IsNotNull (UnityEngine.Object value, System.String message) (at <94c5f4c38cdc42d2b006f8badef04394>:0)
UnityEngine.Assertions.Assert.IsNotNull[T] (T value, System.String message) (at <94c5f4c38cdc42d2b006f8badef04394>:0)
UnityEngine.Assertions.Assert.IsNotNull[T] (T value) (at <94c5f4c38cdc42d2b006f8badef04394>:0)
TeleportInputHandlerAvatarTouch.Start () (at Assets/Oculus/SampleFramework/Core/Locomotion/Scripts/TeleportInputHandlerAvatarTouch.cs:118)